
"use client";

import { useEffect, useState } from "react";
import { Card } from "@/components/ui";
import { api } from "@/lib/api";
import { Sparkles, RefreshCcw } from "lucide-react";

export function AISummaryCard() {
    const [summary, setSummary] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [refreshing, setRefreshing] = useState(false);

    async function fetchSummary() {
        try {
            setLoading(true);
            const data = await api.ai.getExecutiveSummary();
            setSummary(data);
        } catch (error) {
            console.error("Failed to fetch AI summary:", error);
        } finally {
            setLoading(false);
            setRefreshing(false);
        }
    }

    useEffect(() => {
        fetchSummary();
    }, []);

    const handleRefresh = () => {
        setRefreshing(true);
        fetchSummary();
    };

    if (loading) {
        return (
            <Card>
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
                    <div className="skeleton" style={{ width: 32, height: 32, borderRadius: 8 }} />
                    <div className="skeleton" style={{ width: 200, height: 24, borderRadius: 4 }} />
                </div>
                <div className="skeleton" style={{ height: 100, borderRadius: 8 }} />
            </Card>
        );
    }

    if (!summary) return null;

    return (
        <Card
            title="AI Executive Summary"
            subtitle={`Generated by ${summary.model || "Gemini AI"}`}
            icon={<Sparkles style={{ color: "#8b5cf6" }} />}
            headerAction={
                <button
                    onClick={handleRefresh}
                    style={{
                        background: "none",
                        border: "none",
                        color: refreshing ? "#8b5cf6" : "#64748b",
                        cursor: "pointer",
                        transition: "all 0.2s",
                        transform: refreshing ? "rotate(180deg)" : "none",
                    }}
                >
                    <RefreshCcw size={16} />
                </button>
            }
        >
            <div
                style={{
                    color: "#cbd5e1",
                    lineHeight: 1.6,
                    fontSize: "0.95rem",
                    whiteSpace: "pre-wrap",
                    background: "rgba(139, 92, 246, 0.05)",
                    padding: 20,
                    borderRadius: 12,
                    border: "1px solid rgba(139, 92, 246, 0.2)",
                }}
            >
                {summary.executive_summary}
            </div>
            {summary.ai_powered && (
                <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 12 }}>
                    <span
                        style={{
                            fontSize: "0.75rem",
                            color: "#8b5cf6",
                            display: "flex",
                            alignItems: "center",
                            gap: 4
                        }}
                    >
                        <Sparkles size={12} /> Powered by Gemini 2.5 Flash
                    </span>
                </div>
            )}
        </Card>
    );
}
